2020-05-25 17:59:28,280 ERROR: Exception on /user/edwinchan10 [GET] [in c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\MiahH\Downloads\VirtualFridge-master-new\app\main\routes.py", line 63, in user
    return render_template('user.html', user=user)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\MiahH\Downloads\VirtualFridge-master-new\app\templates\user.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\MiahH\Downloads\VirtualFridge-master-new\app\templates\layout.html", line 43, in top-level template code
    {% block content %}
  File "C:\Users\MiahH\Downloads\VirtualFridge-master-new\app\templates\user.html", line 14, in block "content"
    <p><a href="{{ url_for('edit_profile') }}">Edit profile</a></p>
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'main.edit_profile' instead?
2020-05-25 17:59:28,288 ERROR: Exception on /user/edwinchan10 [GET] [in c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\MiahH\Downloads\VirtualFridge-master-new\app\main\routes.py", line 63, in user
    return render_template('user.html', user=user)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\MiahH\Downloads\VirtualFridge-master-new\app\templates\user.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "C:\Users\MiahH\Downloads\VirtualFridge-master-new\app\templates\layout.html", line 43, in top-level template code
    {% block content %}
  File "C:\Users\MiahH\Downloads\VirtualFridge-master-new\app\templates\user.html", line 14, in block "content"
    <p><a href="{{ url_for('edit_profile') }}">Edit profile</a></p>
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\miahh\appdata\local\programs\python\python38-32\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'main.edit_profile' instead?
2020-05-25 18:53:23,154 INFO: Virtualfridge startup [in C:\Users\MiahH\Downloads\VirtualFridge-master-new\app\__init__.py:70]
